/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Body {
  static empty(): Body
  static string(body: string): Body
}

export declare class Bytes {
  constructor()
  static fromOwner(owner: Buffer): Bytes
  get length(): number
  isEmpty(): boolean
  isUnique(): boolean
  static copyFromSlice(data: Uint8Array): Bytes
  slice(startIdx: number, endIdx: number): Bytes
  sliceRef(subset: Uint8Array): Bytes
  splitOff(mid: number): Bytes
  splitTo(at: number): Bytes
  truncate(len: number): void
  clear(): void
}

export declare class Full {
  constructor(data: Buffer)
  static fromBytes(data: Bytes): Full
}

export declare class Method {
  static connect(): Method
  static delete(): Method
  static get(): Method
  static head(): Method
  static options(): Method
  static patch(): Method
  static post(): Method
  static put(): Method
  static trace(): Method
  static fromBytes(src: Uint8Array): Method
  isIndempotent(): boolean
  toString(): string
}

export declare class Request {
  static builder(): Request
  static get(uri: string): Request
  static put(uri: string): Request
  static post(uri: string): Request
  static delete(uri: string): Request
  static options(uri: string): Request
  static head(uri: string): Request
  static connect(uri: string): Request
  static patch(uri: string): Request
  static trace(uri: string): Request
  constructor(body: Body)
  static fromParts(): Request
  method(): Method
  uri(): string
  version(): Version
  headers(): object
  body(): Body
}

export declare class RequestBuilder {
  constructor()
  method(method: Method): RequestBuilder
  getMethod(): Method | null
  uri(uri: string): RequestBuilder
  getUri(): string | null
  version(version: Version): RequestBuilder
  getVersion(): Version | null
  header(key: string, value: string): RequestBuilder
  getHeaders(): object | null
  headersMut(): void
  extension(): void
  getExtensions(): void
  extensionsMut(): void
  body(body: Body): Request
}

export declare class RequestContext {
  get request(): Request
  get requestId(): number
}

export declare class Response {
  static builder(): ResponseBuilder
  constructor(body: Body)
  static fromParts(): Response
  status(): StatusCode
  version(): Version
  headers(): object
  body(): Body
}

export declare class ResponseBuilder {
  constructor()
  status(status: StatusCode): ResponseBuilder
  version(version: Version): ResponseBuilder
  header(key: string, value: string): ResponseBuilder
  getHeaders(): object | null
  headersMut(): void
  extension(): void
  getExtensions(): void
  extensionsMut(): void
  body(body: Body): Response
}

/**
 * A simple, thread-safe router for path matching
 *
 * This router only handles path matching. Handler management
 * and invocation should be done in JavaScript for simplicity.
 *
 * # JavaScript Usage Example:
 *
 * ```javascript
 * const { Router, Request, Response, Body, StatusCode } = require('./index');
 *
 * // Create router
 * const router = new Router();
 *
 * // Store handlers in JavaScript (simpler and more flexible)
 * const handlers = new Map();
 *
 * // Register routes and handlers
 * function register(path, handler) {
 *   router.addRoute(path);
 *   handlers.set(path, handler);
 * }
 *
 * register('/users', async (req) => {
 *   return Response.builder()
 *     .status(StatusCode.ok())
 *     .body(Body.string('Users'));
 * });
 *
 * register('/posts', (req) => {
 *   return Response.builder()
 *     .status(StatusCode.ok())
 *     .body(Body.string('Posts'));
 * });
 *
 * // Handle requests
 * async function handleRequest(request) {
 *   const path = request.uri();
 *
 *   if (router.hasRoute(path)) {
 *     const handler = handlers.get(path);
 *     if (handler) {
 *       return await handler(request);
 *     }
 *   }
 *
 *   return Response.builder()
 *     .status(StatusCode.notFound())
 *     .body(Body.string(`Not Found: ${path}`));
 * }
 *
 * // Use with Node.js http server or in hyper service
 * ```
 */
export declare class Router {
  /** Create a new router */
  constructor()
  /**
   * Add a route to the router
   *
   * @param path - The path to register (e.g., "/users")
   * @param method - Optional HTTP method (e.g., "GET", "POST")
   */
  addRoute(path: string, method?: string | undefined | null): void
  /**
   * Remove a route from the router
   *
   * @returns true if the route existed and was removed
   */
  removeRoute(path: string): boolean
  /**
   * Check if a route exists
   *
   * @param path - The path to check
   * @returns true if the route is registered
   */
  hasRoute(path: string): boolean
  /**
   * Find a route and get its info
   *
   * @param path - The path to look up
   * @returns RouteInfo if found, null otherwise
   */
  findRoute(path: string): RouteInfo | null
  /**
   * Get all registered routes
   *
   * @returns Array of all route paths
   */
  getRoutes(): Array<string>
  /**
   * Get all route information
   *
   * @returns Array of RouteInfo objects
   */
  getRouteInfo(): Array<RouteInfo>
  /** Clear all routes */
  clear(): void
  /** Get the number of registered routes */
  count(): number
}

/** HTTP Server that integrates with JavaScript handlers via Router */
export declare class Server {
  /** Create a new server with a router */
  constructor(router: Router)
  setHandler(handler: (arg: RequestContext) => void): void
  listen(addr: string): void
  /** Start the server on the specified address */
  listenBkp(addr: string): void
  getRouter(): Router
}

export declare class StatusCode {
  static fromU16(src: number): StatusCode
  static fromBytes(src: Uint8Array): StatusCode
  toString(): string
  canonicalReason(): string | null
  isInformational(): boolean
  isSuccess(): boolean
  isRedirection(): boolean
  isClientError(): boolean
  static continue(): StatusCode
  static switchingProtocols(): StatusCode
  static processing(): StatusCode
  static ok(): StatusCode
  static created(): StatusCode
  static accepted(): StatusCode
  static nonAuthoritativeInformation(): StatusCode
  static noContent(): StatusCode
  static resetContent(): StatusCode
  static partialContent(): StatusCode
  static multiStatus(): StatusCode
  static alreadyReported(): StatusCode
  static imUsed(): StatusCode
  static multipleChoices(): StatusCode
  static movedPermanently(): StatusCode
  static found(): StatusCode
  static seeOther(): StatusCode
  static notModified(): StatusCode
  static useProxy(): StatusCode
  static temporaryRedirect(): StatusCode
  static permanentRedirect(): StatusCode
  static badRequest(): StatusCode
  static unauthorized(): StatusCode
  static paymentRequired(): StatusCode
  static forbidden(): StatusCode
  static notFound(): StatusCode
  static methodNotAllowed(): StatusCode
  static notAcceptable(): StatusCode
  static proxyAuthenticationRequired(): StatusCode
  static requestTimeout(): StatusCode
  static conflict(): StatusCode
  static gone(): StatusCode
  static lengthRequired(): StatusCode
  static preconditionFailed(): StatusCode
  static payloadTooLarge(): StatusCode
  static uriTooLong(): StatusCode
  static unsupportedMediaType(): StatusCode
  static rangeNotSatisfiable(): StatusCode
  static expectationFailed(): StatusCode
  static imATeapot(): StatusCode
  static misdirectedRequest(): StatusCode
  static unprocessableEntity(): StatusCode
  static locked(): StatusCode
  static failedDependency(): StatusCode
  static tooEarly(): StatusCode
  static upgradeRequired(): StatusCode
  static preconditionRequired(): StatusCode
  static tooManyRequests(): StatusCode
  static requestHeaderFieldsTooLarge(): StatusCode
  static unavailableForLegalReasons(): StatusCode
  static internalServerError(): StatusCode
  static notImplemented(): StatusCode
  static badGateway(): StatusCode
  static serviceUnavailable(): StatusCode
  static gatewayTimeout(): StatusCode
  static httpVersionNotSupported(): StatusCode
  static variantAlsoNegotiates(): StatusCode
  static insufficientStorage(): StatusCode
  static loopDetected(): StatusCode
  static notExtended(): StatusCode
  static networkAuthenticationRequired(): StatusCode
}

export declare class Version {
  static http09(): Version
  static http10(): Version
  static http11(): Version
  static http2(): Version
  static http3(): Version
}

/** Complete the handling of a request by sending back a response */
export declare function completeRequest(requestId: number, response: Response): void

export interface RouteInfo {
  path: string
  method?: string
}
