/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Bytes {
  constructor()
  static fromOwner(owner: Buffer): Bytes
  get length(): number
  isEmpty(): boolean
  isUnique(): boolean
  static copyFromSlice(data: Uint8Array): Bytes
  slice(startIdx: number, endIdx: number): Bytes
  sliceRef(subset: Uint8Array): Bytes
  splitOff(mid: number): Bytes
  splitTo(at: number): Bytes
  truncate(len: number): void
  clear(): void
}

export declare class JsTextOptions {
  constructor(options: TextOptionsNewParams)
  verify(verifyFn: (arg0: Request, arg1: Response, arg2: Buffer, arg3: string) => void): void
}

export declare class Method {
  static connect(): Method
  static delete(): Method
  static get(): Method
  static head(): Method
  static options(): Method
  static patch(): Method
  static post(): Method
  static put(): Method
  static trace(): Method
  static fromBytes(src: Uint8Array): Method
  isIndempotent(): boolean
  toString(): string
}

export declare class Request {
  /**
   * Checks if the specified content types are acceptable, based on the
   * request’s Accept HTTP header field. The method returns the best match, or
   * if none of the specified content types is acceptable, returns false (in
   * which case, the application should respond with 406 "Not Acceptable").
   *
   * The type value may be a single MIME type string (such as
   * "application/json"), an extension name such as "json", a comma-delimited
   * list, or an array. For a list or array, the method returns the best match
   * (if any).
   *
   * ```javascript
   * // Accept: text/html
   * req.accepts('html')
   * // => "html"
   *
   * // Accept: text/*, application/json
   * req.accepts('html')u
   * // => "html"
   * req.accepts('text/html')
   * // => "text/html"
   * req.accepts(['json', 'text'])
   * // => "json"
   * req.accepts('application/json')
   * // => "application/json"
   *
   * // Accept: text/*, application/json
   * req.accepts('image/png')
   * req.accepts('png')
   * // => false
   *
   * // Accept: text/*;q=.5, application/json
   * req.accepts(['html', 'json'])
   * // => "json"
   * ```
   *
   * For more information, or if you have issues or concerns, see
   * [accepts](https://github.com/expressjs/accepts).
   */
  accepts(types: string | Array<string>): string | Array<string> | null
  /**
   * Returns the specified HTTP request header field (case-insensitive match).
   * The `Referrer` and `Referer` fields are interchangeable.
   *
   * ```javascript
   * req.get('Content-Type')
   * // => "text/plain"
   *
   * req.get('content-type')
   * // => "text/plain"
   *
   * req.get('Something')
   * // => undefined
   * ```
   *
   * Aliased as `req.header(field)`.
   */
  get(field: string): string | Buffer
  header(field: string): string | Buffer
  get params(): object
  /**
   * Included for test purposes. Normally, you will obtain a request from the
   * server
   */
  constructor()
  /**
   * `req.body`'s shape is based on user-controlled input, all properties and
   * values in this object are untrusted and should be validated before
   * trusting. For example, `req.body.foo.toString()` may fail in multiple
   * ways, for example the foo property may not be there or may not be a
   * string, and `toString` may not be a function and instead a string or
   * other user input.
   */
  get body(): string | unknown | null
}

export declare class Response {
  /**
   * Appends the specified value to the HTTP response header field. If the header is not already set, it creates the header
   * with the specified value. The value parameter can be a string or an array.
   * > **&#10155; Note**
   * >
   * > calling `res.set()` after `res.append()` will reset the previously-set header value.
   *
   * ```javascript
   * res.append('Link', ['<http://localhost/>', '<http://localhost:3000/>'])
   * res.append('Set-Cookie', 'foo=bar; Path=/; HttpOnly')
   * res.append('Warning', '199 Miscellaneous warning')
   * ```
   */
  append(field: string, value: Array<string> | string): void
  /**
   * Sets the HTTP response Content-Disposition header field to "attachment". If a file_path is given, then it sets the
   * Content-Type based on the extension name via res.type(), and sets the Content-Disposition "filename=" parameter.
   *
   * ```javascript
   * res.attachment()
   * // Content-Disposition: attachment
   *
   * res.attachment('path/to/logo.png')
   * // Content-Disposition: attachment; filename="logo.png"
   * // Content-Type: image/png
   * ```
   */
  attachment(filePath?: string | undefined | null): void
  /**
   * Clears the cookie with the specified name by sending a `Set-Cookie` header that sets its expiration date in the past.
   * This instructs the client that the cookie has expired and is no longer valid. For more information about available
   * options, see `res.cookie()`.
   *
   * > The expires and max-age options are being ignored completely.
   *
   * > Web browsers and other compliant clients will only clear the cookie if the given options is identical to those given
   * > to res.cookie()
   *
   * ```javascript
   * res.cookie('name', 'tobi', { path: '/admin' })
   * res.clearCookie('name', { path: '/admin' })
   * ```
   */
  clearCookie(name: string, options?: CookieOptions | undefined | null): void
  /**
   * Sets the `Content-Type` HTTP header to the MIME type as determined by the specified
   * `type`. If `type` contains the "/" character, then it sets the `Content-Type` to
   * the exact value of `type`, otherwise it is assumed to be a file extension and the
   * MIME type is looked up using the `from_ext()` method of the mime_guess crate. When
   * no mapping is found though `mime_guess::from_ext()`, the type is set to
   * "application/octet-stream".
   *
   *  Examples:
   *
   *  ```javascript
   *      res.type('.html'); // => 'text/html'
   *      res.type('html'); // => 'text/html'
   *      res.type('json'); // => 'application/json'
   *      res.type('application/json'); // => 'application/json'
   *      res.type('png'); // => image/png
   * ```
   *
   * Aliased as `res.contentType(type)`.
   */
  type(typ: string): void
  contentType(typ: string): void
  /**
   * Sets cookie `name` to `value`. The `value` parameter may be a string or object converted to JSON.
   *
   * The `options` parameter is an object that can have the following properties.
   *
   * | Property      | Type     | Description |
   * | --------      | -----    | --- |
   * | `domain`      | String   | Domain name for the cookie. Defaults to the domain name of the app. |
   * | `encode`      | Function | A synchronous function used for cookie value encoding. Defaults to `encodeURIComponent`. |
   * | `expires`     | Date     | Expiry date of the cookie in GMT. If not specified or set to 0, creates a session cookie. |
   * | `httpOnly`    | Boolean  | Flags the cookie to be accessible only by the web server. |
   * | `maxAge`      | Number   | Convenient option for setting the expiry time relative to the current time in milliseconds. |
   * | `path`        | String   | Path for the cookie. Defaults to "/". |
   * | `partitioned` | Boolean  | Indicates that the cookie should be stored using partitioned storage. See [Cookies Having Independent Partitioned State (CHIPS)](https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies) for more details. |
   * | `priority`    | String   | Value of the "Priority" Set-Cookie attribute. |
   * | `secure`      | Boolean  | Marks the cookie to be used with HTTPS only. |
   * | `signed`      | Boolean  | Indicates if the cookie should be signed. |
   * | `sameSite`    | Boolean or String | Value of the "SameSite" Set-Cookie attribute. More information at https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site-00#section-4.1.1. |
   *
   * > All `res.cookie()` does is set the HTTP `Set-Cookie` header with the options provided. Any option not specified defaults to the value stated in [RFC 6265](http://tools.ietf.org/html/rfc6265).
   *
   * For example:
   *
   * ```javascript
   * res.cookie('name', 'tobi', { domain: '.example.com', path: '/admin', secure: true })
   * res.cookie('rememberme', '1', { expires: new Date(Date.now() + 900000), httpOnly: true })
   * ```
   *
   * You can set multiple cookies in a single response by calling res.cookie multiple times, for example:
   *
   * ```javascript
   * res
   *   .status(201)
   *   .cookie('access_token', `Bearer ${token}`, {
   *     expires: new Date(Date.now() + 8 * 3600000) // cookie will be removed after 8 hours
   *   })
   *   .cookie('test', 'test')
   *   .redirect(301, '/admin')
   * ```
   *
   * The encode option allows you to choose the function used for cookie value encoding. Does not support asynchronous functions.
   *
   * Example use case: You need to set a domain-wide cookie for another site in your organization. This other site (not under your administrative control) does not use URI-encoded cookie values.
   *
   * ```javascript
   * // Default encoding
   * res.cookie('some_cross_domain_cookie', 'http://mysubdomain.example.com', { domain: 'example.com' })
   * // Result: 'some_cross_domain_cookie=http%3A%2F%2Fmysubdomain.example.com; Domain=example.com; Path=/'
   *
   * // Custom encoding
   * res.cookie('some_cross_domain_cookie', 'http://mysubdomain.example.com', { domain: 'example.com', encode: String })
   * // Result: 'some_cross_domain_cookie=http://mysubdomain.example.com; Domain=example.com; Path=/;'
   * ```
   *
   * The maxAge option is a convenience option for setting "expires" relative to the current time in milliseconds. The following is equivalent to the second example above.
   *
   * ```javascript
   * res.cookie('rememberme', '1', { maxAge: 900000, httpOnly: true })
   * ```
   *
   * You can pass an object as the value parameter; it is then serialized as JSON and parsed by bodyParser() middleware.
   *
   * ```javascript
   * res.cookie('cart', { items: [1, 2, 3] })
   * res.cookie('cart', { items: [1, 2, 3] }, { maxAge: 900000 })
   * ```
   *
   * When using cookie-parser middleware, this method also supports signed cookies. Simply include the signed option set to true. Then, res.cookie() will use the secret passed to cookieParser(secret) to sign the value.
   *
   * ```javascript
   * res.cookie('name', 'tobi', { signed: true })
   * ```
   *
   * Later, you may access this value through the `req.signedCookies` object.
   */
  cookie(name: string, value: string, options?: CookieOptions | undefined | null): void
  /**
   *  Performs content-negotiation on the Accept HTTP header on the request
   *  object, when present. It uses `req.accepts()` to select a handler for the
   *  request, based on the acceptable types ordered by their quality values.
   *  If the header is not specified, the first callback is invoked. When no
   *  match is found, the server responds with 406 "Not Acceptable", or invokes
   *  the default callback.
   *
   *  The `Content-Type` response header is set when a callback is selected.
   *  However, you may alter this within the callback using methods such as
   *  `res.set()` or `res.type()`.
   *
   *  The following example would respond with `{ "message": "hey" }` when the
   *  Accept header field is set to "application/json" or "*&#8203;/json" (however, if
   *  it is "*&#8203;/*", then the response will be "hey").
   *
   * ```javascript
   *  res.format({
   *    'text/plain' () {
   *      res.send('hey')
   *    },
   *
   *    'text/html' () {
   *      res.send('<p>hey</p>')
   *    },
   *
   *    'application/json' () {
   *      res.send({ message: 'hey' })
   *    },
   *
   *    default () {
   *      // log the request and respond with 406
   *      res.status(406).send('Not Acceptable')
   *    }
   *  })
   *  ```
   *
   *  In addition to canonicalized MIME types, you may also use extension names
   *  mapped to these types for a slightly less verbose implementation:
   *
   *  ```javascript
   *  res.format({
   *    text () {
   *      res.send('hey')
   *    },
   *
   *    html () {
   *      res.send('<p>hey</p>')
   *    },
   *
   *    json () {
   *      res.send({ message: 'hey' })
   *    }
   *  })
   *  ```
   */
  format(obj: object): Promise<Response>
  /**
   * Returns the HTTP response header specified by `field`. The match is case-insensitive.
   *
   * ```javascript
   * res.get('Content-Type')
   * // => "text/plain"
   * ```
   */
  get(field: string): string | Buffer
  /**
   * Sends a JSON response. This method sends a response (with the correct
   * content-type) that is the parameter converted to a JSON string using
   * JSON.stringify().
   *
   * The parameter can be any JSON type, including object, array, string,
   * Boolean, number, or null, and you can also use it to convert other values
   * to JSON.
   *
   * ```javascript
   * res.json(null)
   * res.json({ user: 'tobi' })
   * res.status(500).json({ error: 'message' })
   * ```
   */
  json(body: string | number | boolean | object | null): void
  /**
   * Joins the links provided as properties of the parameter to populate the response’s Link HTTP header field.
   *
   * For example, the following call:
   *
   * ```javascript
   * res.links({
   *   next: 'http://api.example.com/users?page=2',
   *   last: 'http://api.example.com/users?page=5'
   * })
   * ```
   *
   * Yields the following results:
   *
   * ```text
   * Link: <http://api.example.com/users?page=2>; rel="next",
   *       <http://api.example.com/users?page=5>; rel="last"
   * ```
   */
  links(links: object): void
  /**
   * Sends the HTTP response.
   *
   * The body parameter can be a Buffer object, a String, an object, Boolean, or
   * an Array. For example:
   *
   * ```javascript
   * res.send(Buffer.from('whoop'))
   * res.send({ some: 'json' })
   * res.send('<p>some html</p>')
   * res.status(404).send('Sorry, we cannot find that!')
   * res.status(500).send({ error: 'something blew up' })
   * ```
   *
   * This method performs many useful tasks for simple non-streaming responses:
   * For example, it automatically assigns the Content-Length HTTP response
   * header field and provides automatic HEAD and HTTP cache freshness support.
   *
   * When the parameter is a Buffer object, the method sets the Content-Type
   * response header field to "application/octet-stream", unless previously
   * defined as shown below:
   *
   * ```javascript
   * res.set('Content-Type', 'text/html')
   * res.send(Buffer.from('<p>some html</p>'))
   * ```
   *
   * When the parameter is a String, the method sets the Content-Type to
   * "text/html":
   *
   * ```javascript
   * res.send('<p>some html</p>')
   * ```
   *
   * When the parameter is an Array or Object, Express responds with the JSON
   * representation:
   *
   * ```javascript
   * res.send({ user: 'tobi' })
   * res.send([1, 2, 3])
   * ```
   */
  send(body: string | number | boolean | object | null | Buffer): void
  /**
   * Sets the response HTTP status code to statusCode and sends the registered
   * status message as the text response body. If an unknown status code is
   * specified,`res.statusCode` will throw an error
   *
   * ```javascript
   * res.sendStatus(404)
   * ```
   */
  sendStatus(body: number | StatusCode): void
  /**
   * Sets the response’s HTTP header field to value. To set multiple fields at
   * once, pass an object as the parameter.
   *
   * ```javascript
   * res.set('Content-Type', 'text/plain')
   *
   * res.set({
   *   'Content-Type': 'text/plain',
   *   'Content-Length': '123',
   *   ETag: '12345',
   *   Link: ['<http://localhost/>', '<http://localhost:3000/>']
   * })
   * ```
   *
   * Aliased as res.header(field [, value]).
   */
  set(field: string | object, value?: string | undefined | null): void
  /**
   * Sets the HTTP status for the response.
   *
   * ```javascript
   * res.status(403).end()
   * res.status(400).send('Bad Request')
   * res.status(404).sendFile('/absolute/path/to/404.png')
   * ```
   */
  status(body: number | StatusCode): Response
  /**
   * Adds the field to the `Vary` response header, if it is not there already.
   *
   * ``` javascript
   * res.vary('User-Agent').render('docs')
   * ```
   */
  vary(field: string): void
  constructor()
  end(): void
  get req(): Request
}

/** HTTP Server that integrates with JavaScript handlers via Router */
export declare class Server {
  /** Create a new server with a router */
  constructor()
  get(route: string, handler: JsHandlerFunction): void
  post(route: string, handler: JsHandlerFunction): void
  use(route: string | undefined | null, middleware: JsMiddlewareFunction): void
  listen(addr: string): void
}

export declare class StatusCode {
  static fromU16(src: number): StatusCode
  static fromBytes(src: Uint8Array): StatusCode
  toString(): string
  canonicalReason(): string | null
  isInformational(): boolean
  isSuccess(): boolean
  isRedirection(): boolean
  isClientError(): boolean
  static continue(): StatusCode
  static switchingProtocols(): StatusCode
  static processing(): StatusCode
  static ok(): StatusCode
  static created(): StatusCode
  static accepted(): StatusCode
  static nonAuthoritativeInformation(): StatusCode
  static noContent(): StatusCode
  static resetContent(): StatusCode
  static partialContent(): StatusCode
  static multiStatus(): StatusCode
  static alreadyReported(): StatusCode
  static imUsed(): StatusCode
  static multipleChoices(): StatusCode
  static movedPermanently(): StatusCode
  static found(): StatusCode
  static seeOther(): StatusCode
  static notModified(): StatusCode
  static useProxy(): StatusCode
  static temporaryRedirect(): StatusCode
  static permanentRedirect(): StatusCode
  static badRequest(): StatusCode
  static unauthorized(): StatusCode
  static paymentRequired(): StatusCode
  static forbidden(): StatusCode
  static notFound(): StatusCode
  static methodNotAllowed(): StatusCode
  static notAcceptable(): StatusCode
  static proxyAuthenticationRequired(): StatusCode
  static requestTimeout(): StatusCode
  static conflict(): StatusCode
  static gone(): StatusCode
  static lengthRequired(): StatusCode
  static preconditionFailed(): StatusCode
  static payloadTooLarge(): StatusCode
  static uriTooLong(): StatusCode
  static unsupportedMediaType(): StatusCode
  static rangeNotSatisfiable(): StatusCode
  static expectationFailed(): StatusCode
  static imATeapot(): StatusCode
  static misdirectedRequest(): StatusCode
  static unprocessableEntity(): StatusCode
  static locked(): StatusCode
  static failedDependency(): StatusCode
  static tooEarly(): StatusCode
  static upgradeRequired(): StatusCode
  static preconditionRequired(): StatusCode
  static tooManyRequests(): StatusCode
  static requestHeaderFieldsTooLarge(): StatusCode
  static unavailableForLegalReasons(): StatusCode
  static internalServerError(): StatusCode
  static notImplemented(): StatusCode
  static badGateway(): StatusCode
  static serviceUnavailable(): StatusCode
  static gatewayTimeout(): StatusCode
  static httpVersionNotSupported(): StatusCode
  static variantAlsoNegotiates(): StatusCode
  static insufficientStorage(): StatusCode
  static loopDetected(): StatusCode
  static notExtended(): StatusCode
  static networkAuthenticationRequired(): StatusCode
}

export declare class TextMiddleware {
  constructor(options?: JsTextOptions | undefined | null)
  run(request: Request, response: Response): Promise<boolean>
}

export declare class Version {
  static http09(): Version
  static http10(): Version
  static http11(): Version
  static http2(): Version
  static http3(): Version
}

export interface ClearCookie {

}

export interface CookieOptions {
  domain?: string
  encode?: (arg: string) => string
  expires?: Date | ClearCookie
  httpOnly?: boolean
  maxAge?: number
  path?: string
  partitioned?: boolean
  priority?: string
  secure?: boolean
  signed?: boolean
  sameSite?: boolean | string
}

export declare function serializeNapiObject(obj: object): string

export interface TextOptionsNewParams {
  defaultCharset?: string
  inflate?: boolean
  limit?: number
  type?: string
}
